version: '2'
volumes:
    zabbix-server-conf:
    zabbix-server-scripts:
    zabbix-db-data:
    zabbix-agentd-conf:
    zabbix-agentd-scripts:

services:
  db:
    image: gcavalcante8808/zabbix-db-postgres:3.4.5
    restart: always
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: "zabbix"
    volumes:
      - zabbix-db-data:/var/lib/postgresql/data

  agentd:
    image: gcavalcante8808/zabbix-agentd:3.4.0
    restart: always
    environment:
      ZBX_SERVER: 127.0.0.1
      REMOTE_COMMAND: 1
      PROOT_NO_SECCOMP: 1
    network_mode: host
    pid: host
    privileged: true
    volumes:
     - /sys:/sys
     - /sys/fs/cgroup:/sys/fs/cgroup
     - /:/rootfs:ro
     - zabbix-agentd-conf:/usr/local/etc/zabbix_agentd.conf.d/
     - zabbix-agentd-scripts:/usr/local/share/zabbix/external_scripts/  

  server:
    image: gcavalcante8808/zabbix-server:3.4.5
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: zabbix
      DB_PASS: zabbix
      DB_NAME: zabbix
      DB_TYPE: POSTGRESQL
    volumes:
     - zabbix-server-conf:/usr/local/etc/zabbix_server.conf.d
     - zabbix-server-scripts:/usr/local/share/zabbix/externalscripts
    ports:
     - "10051:10051"
    depends_on:
     - db

  frontend:
    image: gcavalcante8808/zabbix-frontend:3.4.5
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: zabbix
      DB_PASS: zabbix
      DB_NAME: zabbix
      DB_TYPE: POSTGRESQL
      ZBX_SERVER: server
      ZBX_SERVER_PORT: 10051
      ZBX_SERVER_NAME: "Zabbix Docker"
    ports:
      - "80:80"
    depends_on:
     - db
     - server

