version: '2'
volumes:
    zabbix-agentd-conf:
    zabbix-agentd-scripts:

services:
    agentd:
      image: gcavalcante8808/zabbix-agentd:3.4.4
      restart: always
      privileged: true
      environment:
        ZBX_SERVER: 127.0.0.1
        REMOTE_COMMAND: 1
        PROOT_NO_SECCOMP: 1
      network_mode: host
      volumes:
       - zabbix-agentd-conf:/usr/local/etc/zabbix_agentd.conf.d
       - zabbix-agentd-scripts:/usr/share/local/zabbix  
      cap_add:
       - SYS_PTRACE
